//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMgmt.MW.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoTietKiem
    {
        public int MaSoTietKiem { get; set; }
        public Nullable<decimal> SoTienGui { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<System.DateTime> NgayDaoHan { get; set; }
        public Nullable<int> KyHan { get; set; }
        public Nullable<double> LaiSuat { get; set; }
        public Nullable<int> MaKHGui { get; set; }
        public Nullable<byte> TinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
