//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMgmt.MW.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichChuyenTien
    {
        public int MaGD { get; set; }
        public Nullable<decimal> SoTienChuyen { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaKHChuyen { get; set; }
        public Nullable<int> MaKHNhan { get; set; }
        public Nullable<int> MaGDVien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhachHang KhachHangNhan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
